export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";


export const ICECREAM_GET = 'ICECREAM_GET';
export const ICECREAM_ADD = 'ICECREAM_ADD';
export const ICECREAM_UPDATE = 'ICECREAM_UPDATE';
export const ICECREAM_DELETE = 'ICECREAM_DELETE';

export const THEME_TOGGLE = 'THEME_TOGGLE';